{"isMarkdown":true,"isTranslated":false,"isActive":true,"flaws":{},"title":"throw","mdn_url":"/en-US/docs/Web/JavaScript/Reference/Statements/throw","locale":"en-US","native":"English (US)","browserCompat":["javascript.statements.throw"],"summary":"The throw statement throws a user-defined exception. Execution of the current function will stop (the statements after throw won't be executed), and control will be passed to the first catch block in the call stack. If no catch block exists among caller functions, the program will terminate.","popularity":0.1126,"modified":"2023-08-11T08:07:46.000Z","source":{"folder":"en-us/web/javascript/reference/statements/throw","github_url":"https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/throw/index.md","last_commit_url":"https://github.com/mdn/content/commit/4c26e8a3fb50d06963b06017f51ce19364350564","filename":"index.md"},"short_title":"throw","parents":[{"uri":"/en-US/docs/Web","title":"References"},{"uri":"/en-US/docs/Web/JavaScript","title":"JavaScript"},{"uri":"/en-US/docs/Web/JavaScript/Reference","title":"Reference"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Statements","title":"Statements and declarations"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Statements/throw","title":"throw"}],"pageTitle":"throw - JavaScript | MDN","noIndexing":false,"hash":"538fbe4eb38cc8a31c6d82d7df9ee049a2d0c505f4a13c30d71a12a914296124"}